name: ais_anomaly_pipeline
version: "1.0.0"
config-version: 2

profile: ais_databricks

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ais_anomaly_pipeline:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
